name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Get current dev build number
        id: dev-build
        run: |
          cd .github/devbuilds
          npm install
          npm run get_number

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pdevbuild=${{ steps.dev-build.outputs.number }}

      - name: Webhook Failure
        if: ${{ failure() }}
        run: |
          cd .github/devbuilds
          npm start ${{ github.ref_name }} https://api.github.com/repos/XaviFortes/serta-client/compare/${{ github.event.before }}...${{ github.event.after }} false
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


      #- name: Publish
      #  run: ./gradlew publish -Pcommit=${{ github.sha }} -Pdevbuild=${{ steps.dev-build.outputs.number }}
      #  env:
      #    MAVEN_METEOR_ALIAS: ${{ secrets.MAVEN_METEOR_ALIAS }}
      #    MAVEN_METEOR_TOKEN: ${{ secrets.MAVEN_METEOR_TOKEN }}

      # Get version from gradle.properties and set as variable
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat gradle.properties | grep "mod_version=" | cut -d'=' -f2)"

      # Upload artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: serta-client-
          path: build/libs/serta-client-*[0-9].jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: serta-client-${{ github.sha }}
          path: build/libs/serta-client-*.jar

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: build/libs/serta-client-*[0-9].jar
          token: ${{ secrets.GITHUB_TOKEN }}
          name: beta v${{ steps.get_version.outputs.version }}-${{ steps.dev-build.outputs.number }}
          tag: ${{ steps.get_version.outputs.version }}
          prerelease: false
          allowUpdates: true
          body: |
            [Changelog](https://github.com/XaviFortes/serta-client/compare/${{ github.event.before }}...${{ github.event.after }})

      - name: Upload file & Discord webhook
        run: |
          cd .github/devbuilds
          npm start ${{ github.ref_name }} https://api.github.com/repos/XaviFortes/serta-client/compare/${{ github.event.before }}...${{ github.event.after }} true
        env:
          # SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
